version: '2'

services:
   mysql:
     image: mysql:5.7.22
     container_name: mysql
     restart: always
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: faveo
       MYSQL_DATABASE: faveo
       MYSQL_USER: faveo
       MYSQL_PASSWORD: faveo
     ports:
       - "3306:3306"

   faveo:
     container_name: faveo
     depends_on:
       - mysql
     image: faveo-dock2.0
     links:
       - mysql:mysql
     ports:
       - "80:80"
     restart: always


volumes:
    db_data:
